version: "3.8"

services:
  api:
    container_name: api
    build: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/logs
    networks:
      - api_network

  postgres:
    container_name: api_postgres
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${PG_DB} -U ${PG_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - api_network


networks:
  api_network:
    driver: bridge